server:
  port: 8087
spring:
  application:
    name: file-service
  security:
    user:
      name: username
      password: password
  mvc:
    servlet:
      path: /file-service
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

