spring:
  application:
    name: auth-service
  mvc:
    servlet:
      path: /auth-service
  datasource:
    url: jdbc:mysql://db-reddit-forum.c5a2iko6s97m.us-east-1.rds.amazonaws.com:3306/USER_DB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: teamproject
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword

security:
  jwt:
    token:
      key: JavaTraining

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    feign.client: DEBUG

