spring:
  application:
    name: message-service
  mvc:
    servlet:
      path: /message-service
  datasource:
    url: jdbc:mysql://db-reddit-forum.c5a2iko6s97m.us-east-1.rds.amazonaws.com:3306/MESSAGE_DB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: teamproject
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework.security: DEBUG

security:
  jwt:
    token:
      key: JavaTraining

server:
  port: 8086

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

