spring:
  application:
    name: history-service
  mvc:
    servlet:
      path: /history-service
  datasource:
    url: jdbc:mysql://db-reddit-forum.c5a2iko6s97m.us-east-1.rds.amazonaws.com:3306/HISTORY_DB
    username: admin
    password: teamproject
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true


server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: JavaTraining