spring:
  application:
    name: history-service
  mvc:
    servlet:
      path: /history-service


server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

