server:
  port: 8081 # The port on which the gateway service is running. Consider using environment-specific configurations to manage different ports across environments.

spring:
  application:
    name: gateway # The name of the application. Useful for service discovery and logging.

  cloud:
    gateway:
      routes:
        - id: user-service # Unique identifier for the route.
          uri: lb://user-service # Specifies the load-balanced backend service URI. Ensure optimal configuration of the load balancer for scalability.
          predicates:
            - Path=/user-service/** # Route requests based on path patterns. Consider dynamic routing strategies for advanced use cases.
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**
        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/history-service/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message-service/**
        - id: post-reply-service
          uri: lb://post-reply-service
          predicates:
            - Path=/post-reply-service/**
eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:http://localhost:8761/eureka} # Service discovery endpoint. For production, secure this URI and consider high availability configurations.
